POST http://localhost:8080/api/users
Content-Type: application/json

{
        "name": "Staiko Dafov",
        "email": "skdafov1@abv.bg",
        "password": "asdQWE123$"
}

###

GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI1ZWM5MjMyMGMyYmJkZDBhZGNhNGEyNWQiLCJpYXQiOjE1OTAyNDAwNzAsImV4cCI6MTU5MDI0NzI3MH0.fWYf1eHxlMpxOLkS3MuvxvAL2OHrVq9JOakqDwAEklE

###

GET http://localhost:8080/api/users/5ec92320c2bbdd0adca4a25d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI1ZWM5MjMyMGMyYmJkZDBhZGNhNGEyNWQiLCJpYXQiOjE1OTAyNDAwNzAsImV4cCI6MTU5MDI0NzI3MH0.fWYf1eHxlMpxOLkS3MuvxvAL2OHrVq9JOakqDwAEklE

###

DELETE  http://localhost:8080/api/users/5ec694d6190cc01c3ae6a65d
###

PATCH http://localhost:8080/api/users/5ec7e54abd51bf53ab73a616
Content-Type: application/json

{
        "name": "Ivan Zhivkov Arabadzhiyski",
        "description": "Mnogo qk user"
}
###

POST http://localhost:8080/api/account/signin
Content-Type: application/json

{
        "email": "skdafov1@abv.bg",
        "password": "asdQWE123$"
}

###

GET http://localhost:8080/api/account/logout
Content-Type: application/json

{
        "token": "5ec6962091f9021d14fc29ae"
}

###

GET http://localhost:8080/api/account/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InByb2ZpbGVQaWN0dXJlIjoiaHR0cHM6Ly9pbWFnZS5zaHV0dGVyc3RvY2suY29tL2ltYWdlLXZlY3Rvci9tYWxlLXNpbGhvdWV0dGUtYXZhdGFyLXByb2ZpbGUtcGljdHVyZS0yNjBudy0xOTkyNDYzODIuanBnIiwiZ2VuZGVyIjoiTSIsInJvbGUiOiJ1c2VyIiwiZGVzY3JpcHRpb24iOiIiLCJ2YWxpZGl0eSI6ImFjdGl2ZSIsInJlZ2lzdGVyRGF0ZSI6IjIwMjAtMDUtMjJUMTI6NDY6NDAuMDgxWiIsIm1vZGlmaWNhdGlvbkRhdGUiOiIyMDIwLTA1LTIyVDEyOjQ2OjQwLjA4MVoiLCJfaWQiOiI1ZWM3YzliODBjM2ZkNDQ2MjQ1ODlhMjAiLCJuYW1lIjoiU3RhaWtvIERhZm92IiwiZW1haWwiOiJza2RhZm92MUBhYnYuYmciLCJwYXNzd29yZCI6IiQyYSQwOCRtY1JlWEM4RHljczBQZHhhdHYyNEtPbUlUUUYzMXhwbjVNTXc0NHhyL3MuTHdmemQxcThIeSIsIl9fdiI6MH0sImlhdCI6MTU5MDE1MjE5MH0.E0e6MbafRtP5G5OwCCGjVO5tz-G3IkdxlqrZz5NRTJA